# Generated by Django 5.2.9 on 2026-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
